package domain.models

import java.time.{Duration, Instant}

final case class Client(
    id: Int,
    enabled: Boolean = true,
    clientId: String,
    protocolType: String = "oidc",
    clientSecrets: List[ClientSecret] = Nil,
    requireClientSecret: Boolean = true,
    clientName: Option[String] = None,
    description: Option[String] = None,
    clientUri: Option[String] = None,
    logoUri: Option[String] = None,
    requireConsent: Boolean = false,
    allowRememberConsent: Boolean = true,
    alwaysIncludeUserClaimsInIdToken: Boolean = false,
    allowedGrantTypes: List[ClientGrantType] = Nil,
    requirePkce: Boolean = true,
    allowPlainTextPkce: Boolean = false,
    requireRequestObject: Boolean = false,
    allowAccessTokensViaBrowser: Boolean = false,
    requireDPoP: Boolean = false,
    dPoPValidationMode: Option[String] = None, // consider sealed trait / enum
    dPoPClockSkew: Duration = Duration.ofMinutes(5),
    redirectUris: List[ClientRedirectUri] = Nil,
    postLogoutRedirectUris: List[ClientPostLogoutRedirectUri] = Nil,
    frontChannelLogoutUri: Option[String] = None,
    frontChannelLogoutSessionRequired: Boolean = true,
    backChannelLogoutUri: Option[String] = None,
    backChannelLogoutSessionRequired: Boolean = true,
    allowOfflineAccess: Boolean = false,
    allowedScopes: List[ClientScope] = Nil,
    identityTokenLifetime: Int = 300,
    allowedIdentityTokenSigningAlgorithms: Option[String] = None,
    accessTokenLifetime: Int = 3600,
    authorizationCodeLifetime: Int = 300,
    consentLifetime: Option[Int] = None,
    absoluteRefreshTokenLifetime: Int = 2592000,
    slidingRefreshTokenLifetime: Int = 1296000,
    refreshTokenUsage: Int =
      1, // (int)TokenUsage.OneTimeOnly in C#; consider modeling TokenUsage as enum
    updateAccessTokenClaimsOnRefresh: Boolean = false,
    refreshTokenExpiration: Int = 1, // (int)TokenExpiration.Absolute
    accessTokenType: Int = 0, // default AccessTokenType.Jwt; consider enum
    enableLocalLogin: Boolean = true,
    identityProviderRestrictions: List[ClientIdPRestriction] = Nil,
    includeJwtId: Boolean = false,
    claims: List[ClientClaim] = Nil,
    alwaysSendClientClaims: Boolean = false,
    clientClaimsPrefix: String = "client_",
    pairWiseSubjectSalt: Option[String] = None,
    allowedCorsOrigins: List[ClientCorsOrigin] = Nil,
    initiateLoginUri: Option[String] = None,
    properties: List[ClientProperty] = Nil,
    userSsoLifetime: Option[Int] = None,
    userCodeType: Option[String] = None,
    deviceCodeLifetime: Int = 300,
    cibaLifetime: Option[Int] = None,
    pollingInterval: Option[Int] = None,
    coordinateLifetimeWithUserSession: Option[Boolean] = None,
    created: Instant = Instant.now(),
    updated: Option[Instant] = None,
    lastAccessed: Option[Instant] = None,
    nonEditable: Boolean = false,
    pushedAuthorizationLifetime: Option[Int] = None,
    requirePushedAuthorization: Boolean = false
)
